
server:
  port: ${LINK_SHORTENER_PORT:8080}
  servlet:
    context-path: /${spring.application.name}

spring:
  profiles:
    active: log-exec-time, localdev
  application:
    name: link-shortener

link-shortener:
  short-link-length: 8
  logging:
    enable-log-execution-time: true